# Generated by Django 2.2 on 2019-05-01 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pserson',
            fields=[
                ('user', models.IntegerField(max_length=128, primary_key=True, serialize=False, unique=True)),
                ('passwd', models.CharField(max_length=128)),
                ('username', models.CharField(max_length=128)),
                ('isDelete', models.BooleanField(default=True)),
            ],
        ),
    ]
