# Generated by Django 2.2 on 2019-05-01 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='pserson',
            new_name='person',
        ),
    ]
