# Generated by Django 2.2 on 2019-05-01 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20190501_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='user',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
