# Generated by Django 2.2 on 2019-05-01 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20190501_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='user',
            field=models.CharField(max_length=128, primary_key=True, serialize=False, unique=True),
        ),
    ]
